@startuml
autonumber
actor ADMIN

activate ADMIN

ADMIN -> UFF_UI: Yêu cầu tạo mới sản phẩm
activate UFF_UI

UFF_UI -> UFF_SERVER: POST api/product
activate UFF_SERVER

UFF_SERVER -> UFF_SERVER: Kiểm tra access token

alt if Token không hợp lệ
UFF_SERVER --> UFF_UI: Trả về lỗi token không hợp lệ
UFF_UI --> ADMIN: Thông báo không có quyền truy cập
end
UFF_SERVER -> UFF_SERVER: Kiểm tra dữ liệu đầu vào

alt if Du lieu dau vao khong hop le
UFF_SERVER --> UFF_UI: Trả về tin nhắn mô tả lỗi tạo mới sản phẩm
UFF_UI --> ADMIN: Thông báo không thể tạo mới sản phẩm
end

UFF_SERVER->UFF_SERVER: Tạo mới sản phẩm dưới CSDL
UFF_SERVER --> UFF_UI: Trả về thông tin dữ liệu vừa được lưu
UFF_UI --> ADMIN: Hiển thị sản phẩm vừa được tạo mới

@enduml