@startuml
autonumber
actor USER

activate USER

USER -> UFF_UI: Yêu cầu lấy danh sách sản phẩm
activate UFF_UI

UFF_UI -> UFF_SERVER: GET api/product?{filter}
activate UFF_SERVER
UFF_SERVER -> UFF_SERVER: Kiểm tra các điều kiện của filter

alt if filter không hợp lệ
UFF_SERVER --> UFF_UI: Trả về tin nhắn lỗi truy vấn
UFF_UI --> USER: Thông báo lỗi và không hiển thị danh sách sản phẩm
end

UFF_SERVER->UFF_SERVER: Truy vấn cơ sở dữ liệu
UFF_SERVER --> UFF_UI: Trả về dữ liệu vừa được truy vấn
UFF_UI --> USER: Hiển thị danh sách sản phẩm

@enduml