@startuml
autonumber
actor ADMIN

activate ADMIN

ADMIN -> UFF_UI: Yeu cau cap nhat san pham
activate UFF_UI

UFF_UI -> UFF_SERVER: PUT api/product/:id
activate UFF_SERVER

UFF_SERVER -> UFF_SERVER: Kiểm tra access token

alt if Token không hợp lệ
UFF_SERVER --> UFF_UI: Trả về lỗi token không hợp lệ
UFF_UI --> ADMIN: Thông báo không có quyền truy cập
end

UFF_SERVER -> UFF_SERVER: Kiểm tra id

alt if id không hợp lệ
UFF_SERVER --> UFF_UI: Trả về tin nhắn mô tả lỗi truy vấn
UFF_UI --> ADMIN:Không tìm thấy sản phẩm để cập nhật
end

UFF_SERVER -> UFF_SERVER: Kiểm tra dữ liệu đầu vào

alt if Dữ liệu đầu vào không hợp lệ
UFF_SERVER --> UFF_UI: Trả về tin nhắn mô tả lỗi cập nhật
UFF_UI --> ADMIN: Không thể cập nhật sản phẩm
end

UFF_SERVER->UFF_SERVER: Cập nhật sản phẩm dưới CSDL
UFF_SERVER --> UFF_UI: Trả về dữ liệu vừa được cập nhật
UFF_UI --> ADMIN: Hiển thị sản phẩm được cập nhật

@enduml