@startuml
autonumber
actor User
activate User
User -> NPS_FE: Yêu cầu xoá nhóm
activate NPS_FE
NPS_FE -> NPS_BE: Gọi api delete api/v1/teams/{teamId}
activate NPS_BE
NPS_BE -> NPS_BE: Kiểm tra token hợp lệ không
alt if token không hợp lệ
NPS_BE --> NPS_FE: trả về tin nhắn token không hợp lệ
NPS_FE --> User: Thông báo người dùng chưa đăng nhập
end
NPS_BE -> NPS_BE: Kiểm tra quyền của user
alt if user không có quyền admin
NPS_BE --> NPS_FE: Trả về lỗi không có quyền
NPS_FE --> User: Thông báo người dùng không có quyền
end
NPS_BE -> NPS_BE: Truy vấn nhóm theo id
alt if nhóm không tồn tại
NPS_BE --> NPS_FE: Trả về lỗi không tìm thấy nhóm
NPS_FE --> User: Thông báo lỗi không tìm thấy nhóm
end
NPS_BE --> NPS_FE: Trả về tin nhắn xoá nhóm thành công
NPS_FE --> User: Hiển thị tin nhắn xoá nhóm thành công
@enduml