@startuml
autonumber
actor USER

activate USER

USER -> UFF_UI: Yêu cầu lấy chi tiết đơn hàng
activate UFF_UI

UFF_UI -> UFF_SERVER: GET api/order/:id
activate UFF_SERVER

UFF_SERVER -> UFF_SERVER: Kiểm tra token hợp lệ không

alt if token không hợp lệ
UFF_SERVER --> UFF_UI: Trả về lỗi token không hợp lệ
UFF_UI --> USER: Thông báo người dùng không có quyền truy cập
end

UFF_SERVER -> UFF_SERVER: Kiểm tra id 

alt if id không hợp lệ
UFF_SERVER --> UFF_UI: Trả về tin nhắn mô tả lỗi truy vấn
UFF_UI --> USER: Không tìm thấy đơn hàng và chuyển trang 404
end

UFF_SERVER->UFF_SERVER: Truy vấn đơn hàng ở CSDL
UFF_SERVER --> UFF_UI: Trả về dữ liệu đơn hàng vừa được truy vấn


UFF_UI --> USER: Hiển thị chi tiết đơn hàng


@enduml