@startuml
autonumber
actor User
activate User
User -> NPS_FE: Yêu cầu danh sách export excel user
activate NPS_FE
NPS_FE -> NPS_BE: Call get api/v1/manager/user/export-excel
activate NPS_BE
NPS_BE -> NPS_BE: Kiểm tra token hợp lệ không
alt if token không hợp lệ
NPS_BE --> NPS_FE: trả về tin nhắn token không hợp lệ
NPS_FE --> User: Thông báo người dùng chưa đăng nhập
end
NPS_BE -> NPS_BE: Kiểm tra quyền của user
alt if user không có quyền admin
NPS_BE --> NPS_FE: Trả về lỗi không có quyền
NPS_FE --> User: Thông báo người dùng không có quyền
end
NPS_BE -> NPS_BE: Truy vấn danh user
NPS_BE -> NPS_BE: Export danh sách user ra excel
NPS_BE --> NPS_FE: Trả về file excel
NPS_FE --> User: Tải file excel về máy người dùng
@enduml