@startuml
autonumber
actor USER
activate USER
USER -> UFF_UI: Yêu cầu quên mật khẩu và nhập email
activate UFF_UI
UFF_UI -> UFF_SERVER: POST api/v1/auth/forgotPassword
activate UFF_SERVER
UFF_SERVER -> UFF_SERVER: Kiểm tra email có hợp lệ không
alt if email không hợp lệ
UFF_SERVER --> UFF_UI: Trả về email không hợp lệ
UFF_UI --> USER: Thông báo cho người dùng email không hợp lệ
end
UFF_SERVER -> UFF_SERVER: Gửi mã xác thực tới email người dùng
UFF_SERVER --> UFF_UI: Yêu cầu quên mật khẩu thành công
UFF_UI --> USER: Chuyển trang xác nhận email
USER -> UFF_UI: Nhập mã xác thực
UFF_UI -> UFF_SERVER: POST api/auth/verify/forgot
UFF_SERVER -> UFF_SERVER: Kiểm tra mã xác thực
alt if Mã xác thực không chính xác
UFF_SERVER --> UFF_UI: Trả về thông tin lỗi
UFF_UI --> USER: Hiển thị thông báo lỗi
end alt
UFF_SERVER -> UFF_SERVER: Tạo ngẫu nhiên mật khẩu mới
UFF_SERVER -> UFF_SERVER: Cập nhật mật khẩu vừa được tạo
UFF_SERVER -> UFF_SERVER: Gửi mật khẩu ngẫu nhiên tới email người dùng
UFF_SERVER --> UFF_UI: Thông báo lấy lại mật khẩu thành công
UFF_UI --> USER: Chuyển trang đăng nhập
@enduml