@startuml
autonumber
actor User
activate User
User -> NPS_FE: Yêu cầu quên mật khẩu và nhập email
activate NPS_FE
NPS_FE -> NPS_BE: POST api/v1/auth/forgotPassword
activate NPS_BE
NPS_BE -> NPS_BE: Kiểm tra email có hợp lệ không
alt if email không hợp lệ
NPS_BE --> NPS_FE: Trả về email không hợp lệ
NPS_FE --> User: Thông báo cho người dùng email không hợp lệ
end
NPS_BE -> NPS_BE: Gửi mã xác thực tới email người dùng
NPS_BE --> NPS_FE: Yêu cầu quên mật khẩu thành công
NPS_FE --> User: Chuyển trang xác nhận email
User -> NPS_FE: Nhập mã xác thực
NPS_FE -> NPS_BE: POST api/auth/verify/forgot
NPS_BE -> NPS_BE: Kiểm tra mã xác thực
alt if Mã xác thực không chính xác
NPS_BE --> NPS_FE: Trả về thông tin lỗi
NPS_FE --> User: Hiển thị thông báo lỗi
end alt
NPS_BE -> NPS_BE: Tạo ngẫu nhiên mật khẩu mới
NPS_BE -> NPS_BE: Cập nhật mật khẩu vừa được tạo
NPS_BE -> NPS_BE: Gửi mật khẩu ngẫu nhiên tới email người dùng
NPS_BE --> NPS_FE: Thông báo lấy lại mật khẩu thành công
NPS_FE --> User: Chuyển trang đăng nhập
@enduml