@startuml
autonumber
actor USER
activate USER
USER -> UFF_UI: Yêu cầu đăng nhập
activate UFF_UI
UFF_UI -> UFF_SERVER: Gọi api/auth/login
activate UFF_SERVER
UFF_SERVER -> UFF_SERVER: Truy vấn USER by email và password
UFF_SERVER -> UFF_SERVER: Kiểm tra USER hợp lệ hay không
alt if người dùng không tồn tại
UFF_SERVER --> UFF_UI: Đăng nhập thất bại
UFF_UI --> USER: Sai email hoặc password
end alt
UFF_SERVER -> UFF_SERVER: Tạo mới AccessToken & Refresh Token
UFF_SERVER --> UFF_UI: Trả về AccessToken & Refresh Token
UFF_UI --> USER: Chuyển người dùng về trang chủ

@enduml