@startuml
autonumber
actor USER
activate USER
USER -> UFF_UI: Yêu cầu làm mới token
activate UFF_UI
UFF_UI -> UFF_SERVER: PUT api/auth/refresh-token
activate UFF_SERVER
UFF_SERVER -> UFF_SERVER: Kiểm tra refresh token có hợp lệ hay không
alt if token không hợp lệ
UFF_SERVER --> UFF_UI: Token không hợp lệ
UFF_UI --> USER: Chuyển người dùng về trang đăng nhập
end 
UFF_SERVER -> UFF_SERVER: Tạo mới accessToken & refreshToen
UFF_SERVER --> UFF_UI: Trả về accessToken & refreshToken
@enduml