@startuml
autonumber
actor USER
activate USER
USER -> UFF_UI: Yều cầu đăng ký tài khoản
activate UFF_UI
UFF_UI -> UFF_SERVER: POST api/auth/register
activate UFF_SERVER
UFF_SERVER -> UFF_SERVER: Kiểm tra email có tồn tại trong database chưa
alt  email đã tồn tại
UFF_SERVER --> UFF_UI: Trả về lỗi email đã tồn tại
UFF_UI --> USER: Hiển thị lỗi email đã tồn tại
end alt
UFF_SERVER -> UFF_SERVER: Gửi mã xác thực đến email được đăng ký
UFF_SERVER --> UFF_UI: Trả về thông tin yêu cầu đăng ký thành công
UFF_UI --> USER: Chuyển trang xác nhận email
USER -> UFF_UI: Nhập mã xác thực
UFF_UI -> UFF_SERVER: POST api/auth/verify/register
UFF_SERVER -> UFF_SERVER: Kiểm tra mã xác thực
alt Mã xác thực không chính xác
UFF_SERVER -> UFF_UI: Trả về thông tin lỗi
UFF_UI -> USER: Hiển thị thông báo lỗi
end alt

UFF_SERVER -> UFF_SERVER: Tạo mới tài khoản dựa trên yêu cầu đăng ký
UFF_SERVER -> UFF_UI: Trả thông tin tài khoản vừa được tạo mới
UFF_UI -> USER: Thông báo đăng ký thành công và chuyển trang đăng nhập

@enduml