@startuml
autonumber
actor User
activate User
User -> NPS_FE: Yêu cầu xem danh sách user đã ở trong workspace
activate NPS_FE
NPS_FE -> NPS_BE: Gọi api/v1/workspace/{workspaceId}/list-user
activate NPS_BE
NPS_BE -> NPS_BE: Kiểm tra token hợp lệ không
alt if token không hợp lệ
NPS_BE --> NPS_FE: trả về tin nhắn token không hợp lệ
NPS_FE --> User: Thông báo người dùng chưa đăng nhập
end
NPS_BE -> NPS_BE: Kiểm tra quyền của user
alt if user không có quyền admin
NPS_BE --> NPS_FE: Trả về lỗi không có quyền
NPS_FE --> User: Thông báo người dùng không có quyền
end
NPS_BE -> NPS_BE: Truy vấn workspace theo id
alt if workspace không tồn tại
NPS_BE --> NPS_FE: Trả về lỗi workspace không tìm thấy
NPS_FE --> User: Thông báo lỗi workspace không tìm thấy
end
NPS_BE -> NPS_BE: Truy vấn danh sách user trong workspace
NPS_BE --> NPS_FE: Trả về danh sách user \nđã ở trong trong workspace
NPS_FE --> User: Hiển thị danh sách user \nđã ở trong trong workspace
@enduml