@startuml
autonumber
actor User
activate User
User -> NPS_FE: Yêu cầu cập nhật contact
activate NPS_FE
NPS_FE -> NPS_BE: Gọi api/v1/contacts
activate NPS_BE
NPS_BE -> NPS_BE: Kiểm tra token hợp lệ không
alt if token không hợp lệ
NPS_BE --> NPS_FE: trả về tin nhắn token không hợp lệ
NPS_FE --> User: Thông báo người dùng chưa đăng nhập
end
NPS_BE -> NPS_BE: Truy vấn contact theo id
alt if contact không tồn tại
NPS_BE --> NPS_FE: trả về tin nhắn không tìm thấy contact
NPS_FE --> User: Thông báo không tìm thấy contact
end
NPS_BE -> NPS_BE: Cập nhật contact theo id
NPS_BE --> NPS_FE: Trả về tin nhắn cập nhật contact thành công
NPS_FE --> User: Thông báo cập nhật contact thành công
@enduml