@startuml
autonumber
actor User
activate User
User -> NPS_FE: Yêu cầu tạo mới label của mailbox
activate NPS_FE
NPS_FE -> NPS_BE: Gọi api/v1/mailbox/labels
activate NPS_BE
NPS_BE -> NPS_BE: Kiểm tra token hợp lệ không
alt if token không hợp lệ
NPS_BE --> NPS_FE: trả về tin nhắn token không hợp lệ
NPS_FE --> User: Thông báo người dùng chưa đăng nhập
end
NPS_BE -> NPS_BE: Tạo mới label
NPS_BE --> NPS_FE: Trả về tin nhắn tạo mới label thành công
NPS_FE --> User: Hiển thị tin nhắn tạo mới label thành công
@enduml