@startuml
autonumber
actor USER
activate USER
USER -> NPS_FE: Yêu cầu đổi mật khẩu
activate NPS_FE
NPS_FE -> NPS_BE: Gọi api/USER/change-password
activate NPS_BE
NPS_BE -> NPS_BE: Kiểm tra access token
alt if token không hợp lệ
NPS_BE --> NPS_FE: Trả về lỗi token không hợp lệ
NPS_FE --> USER: Thông báo lỗi người dùng không có quyền truy cập
end


NPS_BE -> NPS_BE: Kiểm tra currentPassword

alt if currentPassword không hợp lệ
NPS_BE -> NPS_FE: Trả về lỗi mật khẩu hiện tại không hợp lệ
NPS_FE -> USER: Thông báo lỗi mật khẩu hiện tại sai
end alt 

NPS_BE -> NPS_BE: Kiểm tra newPassword và confirmPassword
alt if password không khớp confirmPassword
NPS_BE --> NPS_FE: Trả về lỗi mật khẩu không khớp
NPS_FE --> USER: Hiển thị lỗi mật khẩu không khớp
end
NPS_BE -> NPS_BE: Cập nhật mật khẩu của người dùng
NPS_BE --> NPS_FE: Trả về tin nhắn cập nhật mật khẩu thành công
NPS_FE --> USER: Thông báo cập nhật mật khẩu thành công
@enduml