@startuml
autonumber
actor USER
activate USER
USER -> UFF_UI: Yêu cầu đăng xuất
activate UFF_UI
UFF_UI -> UFF_SERVER: Gọi api/v1/user/logout
activate UFF_SERVER
UFF_SERVER -> UFF_SERVER: Kiểm tra acces token 
alt if token không hợp lệ
UFF_SERVER --> UFF_UI: Trả về lỗi token không hợp lệ
UFF_UI --> USER: Thông báo người dùng không có quyền truy cập
end
UFF_SERVER -> UFF_SERVER: Xoá token của USER dưới redis
UFF_SERVER --> UFF_UI: Trả về tin nhắn đăng xuất thành công
UFF_UI --> USER: Chuyển hướng người dùng về trang chủ
@enduml