@startuml
autonumber
actor USER
activate USER
USER -> NPS_FE: Yêu cầu xem profile
activate NPS_FE
NPS_FE -> NPS_BE: Gọi api/v1/USER/:id
activate NPS_BE
NPS_BE -> NPS_BE: Kiểm tra token có hợp lệ không
alt if token không hợp lệ
NPS_BE --> NPS_FE: Trả về lỗi token không hợp lệ
NPS_FE --> USER: Thông báo lỗi người không có quyền truy cập
end
NPS_BE -> NPS_BE: Truy vấn thông tin USER theo id

alt if USER không tồn tại
NPS_BE -> NPS_FE: Trả về lỗi USER không tồn tại
NPS_FE -> USER: Thông báo lỗi và chuyển trang 404 error
end

NPS_BE --> NPS_FE: Trả về thông tin USER
NPS_FE --> USER: Hiển thị thông tin USER lên màn hình
@enduml